import type { Stock, PricePoint, NewsItem, AIScore, PriceForecast, Sentiment, Impact, Confidence } from '@/types';
import { computeTechnicals } from './indicators';

// Seeded RNG for reproducible demo data
class RNG {
  private seed: number;
  constructor(seed: number) {
    this.seed = seed;
  }
  next(): number {
    this.seed = (this.seed * 9301 + 49297) % 233280;
    return this.seed / 233280;
  }
  range(min: number, max: number): number {
    return min + this.next() * (max - min);
  }
  int(min: number, max: number): number {
    return Math.floor(this.range(min, max + 1));
  }
  pick<T>(arr: T[]): T {
    return arr[Math.floor(this.next() * arr.length)];
  }
}

interface CompanySeed {
  ticker: string;
  name: string;
  sector: string;
  basePrice: number;
  trendBias: number; // -1 to 1, positive = uptrending
  volatility: number; // 0.01 to 0.05
  marketCap: number;
  eps: number;
  peRatio: number;
  revenueGrowth: number;
  profitGrowth: number;
  dividendYield: number;
  debtToEquity: number;
  bookValue: number;
}

const COMPANIES: CompanySeed[] = [
  {
    ticker: 'BEXIMCO',
    name: 'Beximco Limited',
    sector: 'Pharmaceuticals',
    basePrice: 142.5,
    trendBias: 0.35,
    volatility: 0.022,
    marketCap: 38500,
    eps: 12.4,
    peRatio: 11.5,
    revenueGrowth: 18.2,
    profitGrowth: 22.5,
    dividendYield: 3.2,
    debtToEquity: 0.42,
    bookValue: 98.3,
  },
  {
    ticker: 'SQURPHARMA',
    name: 'Square Pharmaceuticals Ltd.',
    sector: 'Pharmaceuticals',
    basePrice: 212.8,
    trendBias: 0.25,
    volatility: 0.018,
    marketCap: 52000,
    eps: 18.6,
    peRatio: 11.4,
    revenueGrowth: 14.5,
    profitGrowth: 16.8,
    dividendYield: 4.1,
    debtToEquity: 0.28,
    bookValue: 145.2,
  },
  {
    ticker: 'GPHOUSE',
    name: 'GPHouse Building Products',
    sector: 'Engineering',
    basePrice: 78.4,
    trendBias: -0.15,
    volatility: 0.028,
    marketCap: 12500,
    eps: 5.2,
    peRatio: 15.1,
    revenueGrowth: 8.4,
    profitGrowth: -3.2,
    dividendYield: 1.8,
    debtToEquity: 0.65,
    bookValue: 52.1,
  },
  {
    ticker: 'WALTONHIL',
    name: 'Walton Hi-Tech Industries',
    sector: 'Engineering',
    basePrice: 568.3,
    trendBias: 0.45,
    volatility: 0.016,
    marketCap: 68000,
    eps: 42.8,
    peRatio: 13.3,
    revenueGrowth: 24.1,
    profitGrowth: 28.5,
    dividendYield: 2.5,
    debtToEquity: 0.31,
    bookValue: 320.5,
  },
  {
    ticker: 'BATBC',
    name: 'British American Tobacco BD',
    sector: 'Food & Allied',
    basePrice: 345.6,
    trendBias: 0.1,
    volatility: 0.014,
    marketCap: 47000,
    eps: 28.5,
    peRatio: 12.1,
    revenueGrowth: 11.2,
    profitGrowth: 9.8,
    dividendYield: 5.2,
    debtToEquity: 0.18,
    bookValue: 210.4,
  },
  {
    ticker: 'OLYMPIC',
    name: 'Olympic Industries Ltd.',
    sector: 'Food & Allied',
    basePrice: 128.9,
    trendBias: -0.3,
    volatility: 0.032,
    marketCap: 8900,
    eps: 4.8,
    peRatio: 26.9,
    revenueGrowth: 5.2,
    profitGrowth: -8.5,
    dividendYield: 1.2,
    debtToEquity: 0.72,
    bookValue: 68.3,
  },
  {
    ticker: 'ROBI',
    name: 'Robi Axiata Limited',
    sector: 'Telecom',
    basePrice: 45.2,
    trendBias: 0.5,
    volatility: 0.026,
    marketCap: 24500,
    eps: 2.1,
    peRatio: 21.5,
    revenueGrowth: 15.8,
    profitGrowth: 35.2,
    dividendYield: 0,
    debtToEquity: 0.55,
    bookValue: 28.9,
  },
  {
    ticker: 'GP',
    name: 'Grameenphone Ltd.',
    sector: 'Telecom',
    basePrice: 298.4,
    trendBias: 0.2,
    volatility: 0.015,
    marketCap: 35000,
    eps: 22.4,
    peRatio: 13.3,
    revenueGrowth: 9.5,
    profitGrowth: 12.1,
    dividendYield: 6.8,
    debtToEquity: 0.12,
    bookValue: 185.6,
  },
  {
    ticker: 'BSCCL',
    name: 'BD Submarine Cable Co.',
    sector: 'Telecom',
    basePrice: 165.7,
    trendBias: -0.2,
    volatility: 0.034,
    marketCap: 6200,
    eps: 8.5,
    peRatio: 19.5,
    revenueGrowth: 3.2,
    profitGrowth: -5.8,
    dividendYield: 2.1,
    debtToEquity: 0.38,
    bookValue: 112.4,
  },
  {
    ticker: 'LHBL',
    name: 'LafargeHolcim Bangladesh',
    sector: 'Cement',
    basePrice: 72.1,
    trendBias: 0.15,
    volatility: 0.024,
    marketCap: 9800,
    eps: 5.8,
    peRatio: 12.4,
    revenueGrowth: 12.5,
    profitGrowth: 14.2,
    dividendYield: 3.5,
    debtToEquity: 0.48,
    bookValue: 55.2,
  },
  {
    ticker: 'IFIC',
    name: 'IFIC Bank Limited',
    sector: 'Bank',
    basePrice: 9.8,
    trendBias: 0.05,
    volatility: 0.02,
    marketCap: 14200,
    eps: 1.2,
    peRatio: 8.2,
    revenueGrowth: 7.5,
    profitGrowth: 6.8,
    dividendYield: 4.5,
    debtToEquity: 0.85,
    bookValue: 14.5,
  },
  {
    ticker: 'BRACBANK',
    name: 'BRAC Bank Limited',
    sector: 'Bank',
    basePrice: 38.5,
    trendBias: 0.3,
    volatility: 0.019,
    marketCap: 7200,
    eps: 4.5,
    peRatio: 8.6,
    revenueGrowth: 16.8,
    profitGrowth: 19.5,
    dividendYield: 3.8,
    debtToEquity: 0.78,
    bookValue: 32.1,
  },
  {
    ticker: 'ABBL',
    name: 'AB Bank Limited',
    sector: 'Bank',
    basePrice: 18.2,
    trendBias: 0.08,
    volatility: 0.021,
    marketCap: 4200,
    eps: 2.1,
    peRatio: 8.7,
    revenueGrowth: 9.2,
    profitGrowth: 8.5,
    dividendYield: 3.5,
    debtToEquity: 0.82,
    bookValue: 22.4,
  },
  {
    ticker: 'CITYBANK',
    name: 'The City Bank Limited',
    sector: 'Bank',
    basePrice: 22.8,
    trendBias: 0.18,
    volatility: 0.02,
    marketCap: 5800,
    eps: 2.8,
    peRatio: 8.1,
    revenueGrowth: 14.2,
    profitGrowth: 16.8,
    dividendYield: 4.2,
    debtToEquity: 0.8,
    bookValue: 26.5,
  },
  {
    ticker: 'PBL',
    name: 'Pubali Bank Limited',
    sector: 'Bank',
    basePrice: 24.5,
    trendBias: 0.05,
    volatility: 0.019,
    marketCap: 5100,
    eps: 2.9,
    peRatio: 8.4,
    revenueGrowth: 8.8,
    profitGrowth: 7.2,
    dividendYield: 3.8,
    debtToEquity: 0.83,
    bookValue: 28.1,
  },
  {
    ticker: 'SBL',
    name: 'Sonali Bank Limited',
    sector: 'Bank',
    basePrice: 28.4,
    trendBias: 0.02,
    volatility: 0.018,
    marketCap: 8200,
    eps: 3.2,
    peRatio: 8.9,
    revenueGrowth: 6.5,
    profitGrowth: 5.8,
    dividendYield: 4.8,
    debtToEquity: 0.88,
    bookValue: 35.2,
  },
  {
    ticker: 'JBL',
    name: 'Janata Bank Limited',
    sector: 'Bank',
    basePrice: 16.8,
    trendBias: -0.05,
    volatility: 0.022,
    marketCap: 3900,
    eps: 1.8,
    peRatio: 9.3,
    revenueGrowth: 5.2,
    profitGrowth: -2.5,
    dividendYield: 3.2,
    debtToEquity: 0.91,
    bookValue: 18.6,
  },
  {
    ticker: 'RBL',
    name: 'Rupali Bank Limited',
    sector: 'Bank',
    basePrice: 19.5,
    trendBias: 0.0,
    volatility: 0.02,
    marketCap: 3200,
    eps: 2.2,
    peRatio: 8.9,
    revenueGrowth: 7.0,
    profitGrowth: 4.5,
    dividendYield: 4.0,
    debtToEquity: 0.86,
    bookValue: 21.8,
  },
  {
    ticker: 'ALBANK',
    name: 'Al-Arafah Islami Bank Ltd.',
    sector: 'Bank',
    basePrice: 21.5,
    trendBias: 0.12,
    volatility: 0.021,
    marketCap: 3800,
    eps: 2.5,
    peRatio: 8.6,
    revenueGrowth: 12.5,
    profitGrowth: 14.8,
    dividendYield: 3.5,
    debtToEquity: 0.79,
    bookValue: 24.2,
  },
  {
    ticker: 'MTBL',
    name: 'Mutual Trust Bank Limited',
    sector: 'Bank',
    basePrice: 14.2,
    trendBias: 0.08,
    volatility: 0.023,
    marketCap: 2100,
    eps: 1.6,
    peRatio: 8.9,
    revenueGrowth: 10.2,
    profitGrowth: 9.5,
    dividendYield: 3.0,
    debtToEquity: 0.84,
    bookValue: 16.8,
  },
  {
    ticker: 'NRBCBANK',
    name: 'NRB Commercial Bank Ltd.',
    sector: 'Bank',
    basePrice: 11.8,
    trendBias: -0.02,
    volatility: 0.025,
    marketCap: 1500,
    eps: 1.1,
    peRatio: 10.7,
    revenueGrowth: 6.8,
    profitGrowth: 2.5,
    dividendYield: 2.5,
    debtToEquity: 0.87,
    bookValue: 13.5,
  },
  {
    ticker: 'SIBL',
    name: 'Social Islami Bank Ltd.',
    sector: 'Bank',
    basePrice: 16.5,
    trendBias: 0.06,
    volatility: 0.022,
    marketCap: 2800,
    eps: 1.9,
    peRatio: 8.7,
    revenueGrowth: 11.2,
    profitGrowth: 10.8,
    dividendYield: 3.2,
    debtToEquity: 0.81,
    bookValue: 19.5,
  },
  {
    ticker: 'DUTCHBANGL',
    name: 'Dutch-Bangla Bank Ltd.',
    sector: 'Bank',
    basePrice: 52.8,
    trendBias: 0.22,
    volatility: 0.017,
    marketCap: 9200,
    eps: 6.2,
    peRatio: 8.5,
    revenueGrowth: 18.5,
    profitGrowth: 21.2,
    dividendYield: 4.5,
    debtToEquity: 0.75,
    bookValue: 48.5,
  },
  {
    ticker: 'EBL',
    name: 'Eastern Bank Limited',
    sector: 'Bank',
    basePrice: 35.2,
    trendBias: 0.15,
    volatility: 0.018,
    marketCap: 6100,
    eps: 4.1,
    peRatio: 8.6,
    revenueGrowth: 13.5,
    profitGrowth: 15.2,
    dividendYield: 4.0,
    debtToEquity: 0.77,
    bookValue: 38.5,
  },
  {
    ticker: 'TRUSTBANK',
    name: 'Trust Bank Limited',
    sector: 'Bank',
    basePrice: 25.8,
    trendBias: 0.1,
    volatility: 0.02,
    marketCap: 3400,
    eps: 2.9,
    peRatio: 8.9,
    revenueGrowth: 11.8,
    profitGrowth: 12.5,
    dividendYield: 3.8,
    debtToEquity: 0.82,
    bookValue: 28.2,
  },
  {
    ticker: 'ONEBANK',
    name: 'One Bank Limited',
    sector: 'Bank',
    basePrice: 13.5,
    trendBias: -0.08,
    volatility: 0.024,
    marketCap: 1800,
    eps: 1.4,
    peRatio: 9.6,
    revenueGrowth: 4.8,
    profitGrowth: -1.5,
    dividendYield: 2.8,
    debtToEquity: 0.88,
    bookValue: 15.2,
  },
  {
    ticker: 'PRAGATIINS',
    name: 'Pragati Insurance Limited',
    sector: 'Insurance',
    basePrice: 32.5,
    trendBias: 0.05,
    volatility: 0.022,
    marketCap: 1200,
    eps: 3.8,
    peRatio: 8.6,
    revenueGrowth: 10.5,
    profitGrowth: 8.2,
    dividendYield: 4.5,
    debtToEquity: 0.15,
    bookValue: 28.5,
  },
  {
    ticker: 'GREENDELT',
    name: 'Green Delta Insurance Ltd.',
    sector: 'Insurance',
    basePrice: 38.2,
    trendBias: 0.12,
    volatility: 0.02,
    marketCap: 1800,
    eps: 4.5,
    peRatio: 8.5,
    revenueGrowth: 15.2,
    profitGrowth: 12.8,
    dividendYield: 5.0,
    debtToEquity: 0.12,
    bookValue: 35.8,
  },
  {
    ticker: 'ICCBANK',
    name: 'ICCB Islamic Bank Ltd.',
    sector: 'Insurance',
    basePrice: 18.5,
    trendBias: -0.05,
    volatility: 0.026,
    marketCap: 800,
    eps: 1.8,
    peRatio: 10.3,
    revenueGrowth: 5.2,
    profitGrowth: -1.8,
    dividendYield: 2.5,
    debtToEquity: 0.22,
    bookValue: 16.2,
  },
  {
    ticker: 'MEGHNA',
    name: 'Meghna Petroleum Limited',
    sector: 'Fuel & Energy',
    basePrice: 285.4,
    trendBias: 0.15,
    volatility: 0.018,
    marketCap: 8500,
    eps: 22.5,
    peRatio: 12.7,
    revenueGrowth: 14.8,
    profitGrowth: 16.5,
    dividendYield: 5.5,
    debtToEquity: 0.25,
    bookValue: 210.5,
  },
  {
    ticker: 'TITASGAS',
    name: 'Titas Gas Transmission',
    sector: 'Fuel & Energy',
    basePrice: 42.8,
    trendBias: 0.08,
    volatility: 0.016,
    marketCap: 12500,
    eps: 4.8,
    peRatio: 8.9,
    revenueGrowth: 10.2,
    profitGrowth: 8.5,
    dividendYield: 5.8,
    debtToEquity: 0.15,
    bookValue: 38.5,
  },
  {
    ticker: 'POWERGRID',
    name: 'Power Grid Co. of BD',
    sector: 'Fuel & Energy',
    basePrice: 56.2,
    trendBias: 0.1,
    volatility: 0.015,
    marketCap: 9800,
    eps: 6.5,
    peRatio: 8.6,
    revenueGrowth: 12.5,
    profitGrowth: 10.8,
    dividendYield: 6.2,
    debtToEquity: 0.2,
    bookValue: 52.8,
  },
  {
    ticker: 'SUMITPOWER',
    name: 'Summit Power Limited',
    sector: 'Fuel & Energy',
    basePrice: 34.5,
    trendBias: 0.05,
    volatility: 0.017,
    marketCap: 4200,
    eps: 3.8,
    peRatio: 9.1,
    revenueGrowth: 8.5,
    profitGrowth: 6.2,
    dividendYield: 5.5,
    debtToEquity: 0.35,
    bookValue: 30.5,
  },
  {
    ticker: 'ENGLISH',
    name: 'English Linen Limited',
    sector: 'Textile',
    basePrice: 68.5,
    trendBias: 0.2,
    volatility: 0.023,
    marketCap: 1500,
    eps: 6.8,
    peRatio: 10.1,
    revenueGrowth: 18.5,
    profitGrowth: 22.2,
    dividendYield: 3.2,
    debtToEquity: 0.42,
    bookValue: 55.8,
  },
  {
    ticker: 'CVCOL',
    name: 'Chittagong Vegetable Oil',
    sector: 'Food & Allied',
    basePrice: 215.8,
    trendBias: 0.18,
    volatility: 0.02,
    marketCap: 3200,
    eps: 18.5,
    peRatio: 11.7,
    revenueGrowth: 16.2,
    profitGrowth: 19.5,
    dividendYield: 4.2,
    debtToEquity: 0.38,
    bookValue: 168.5,
  },
  {
    ticker: 'OLYMPIC2',
    name: 'Olympic Foods Limited',
    sector: 'Food & Allied',
    basePrice: 95.2,
    trendBias: -0.1,
    volatility: 0.028,
    marketCap: 1800,
    eps: 6.2,
    peRatio: 15.4,
    revenueGrowth: 4.5,
    profitGrowth: -2.8,
    dividendYield: 1.5,
    debtToEquity: 0.55,
    bookValue: 72.5,
  },
  {
    ticker: 'AMCL',
    name: 'Agricultural Marketing Co.',
    sector: 'Food & Allied',
    basePrice: 125.5,
    trendBias: 0.08,
    volatility: 0.022,
    marketCap: 2200,
    eps: 9.8,
    peRatio: 12.8,
    revenueGrowth: 11.2,
    profitGrowth: 10.5,
    dividendYield: 3.8,
    debtToEquity: 0.35,
    bookValue: 98.5,
  },
  {
    ticker: 'UNIQUEHRL',
    name: 'Unique Hotel & Resorts Ltd.',
    sector: 'Services & Tourism',
    basePrice: 58.5,
    trendBias: 0.25,
    volatility: 0.02,
    marketCap: 2800,
    eps: 5.2,
    peRatio: 11.3,
    revenueGrowth: 28.5,
    profitGrowth: 32.2,
    dividendYield: 4.5,
    debtToEquity: 0.28,
    bookValue: 45.8,
  },
  {
    ticker: 'BSCCL2',
    name: 'Beximco Synthetics Ltd.',
    sector: 'Textile',
    basePrice: 48.2,
    trendBias: -0.05,
    volatility: 0.026,
    marketCap: 1200,
    eps: 3.5,
    peRatio: 13.8,
    revenueGrowth: 5.8,
    profitGrowth: -1.5,
    dividendYield: 2.2,
    debtToEquity: 0.52,
    bookValue: 38.5,
  },
  {
    ticker: 'BXPHARMA',
    name: 'Beximco Pharmaceuticals Ltd.',
    sector: 'Pharmaceuticals',
    basePrice: 168.5,
    trendBias: 0.28,
    volatility: 0.019,
    marketCap: 11500,
    eps: 14.2,
    peRatio: 11.9,
    revenueGrowth: 19.5,
    profitGrowth: 24.8,
    dividendYield: 3.8,
    debtToEquity: 0.32,
    bookValue: 125.5,
  },
  {
    ticker: 'ACI',
    name: 'ACI Limited',
    sector: 'Food & Allied',
    basePrice: 285.2,
    trendBias: 0.15,
    volatility: 0.018,
    marketCap: 8500,
    eps: 22.8,
    peRatio: 12.5,
    revenueGrowth: 15.8,
    profitGrowth: 18.2,
    dividendYield: 4.2,
    debtToEquity: 0.38,
    bookValue: 215.5,
  },
  {
    ticker: 'BEACO',
    name: 'Beacon Pharmaceuticals Ltd.',
    sector: 'Pharmaceuticals',
    basePrice: 88.5,
    trendBias: 0.32,
    volatility: 0.021,
    marketCap: 3500,
    eps: 7.8,
    peRatio: 11.4,
    revenueGrowth: 25.2,
    profitGrowth: 28.5,
    dividendYield: 2.8,
    debtToEquity: 0.35,
    bookValue: 68.5,
  },
  {
    ticker: 'RENATA',
    name: 'Renata Limited',
    sector: 'Pharmaceuticals',
    basePrice: 1125.8,
    trendBias: 0.2,
    volatility: 0.015,
    marketCap: 15500,
    eps: 85.2,
    peRatio: 13.2,
    revenueGrowth: 17.5,
    profitGrowth: 20.8,
    dividendYield: 3.5,
    debtToEquity: 0.18,
    bookValue: 820.5,
  },
  {
    ticker: 'IBN',
    name: 'Ibn Sina Pharmaceuticals',
    sector: 'Pharmaceuticals',
    basePrice: 95.2,
    trendBias: 0.18,
    volatility: 0.02,
    marketCap: 2800,
    eps: 8.5,
    peRatio: 11.2,
    revenueGrowth: 16.8,
    profitGrowth: 19.2,
    dividendYield: 3.2,
    debtToEquity: 0.3,
    bookValue: 75.8,
  },
  {
    ticker: 'ACIFORMULA',
    name: 'ACI Formulations Ltd.',
    sector: 'Pharmaceuticals',
    basePrice: 78.5,
    trendBias: 0.12,
    volatility: 0.022,
    marketCap: 1800,
    eps: 6.5,
    peRatio: 12.1,
    revenueGrowth: 14.2,
    profitGrowth: 12.8,
    dividendYield: 2.8,
    debtToEquity: 0.38,
    bookValue: 62.5,
  },
  {
    ticker: 'ORIONPHARM',
    name: 'Orion Pharma Ltd.',
    sector: 'Pharmaceuticals',
    basePrice: 125.8,
    trendBias: 0.22,
    volatility: 0.019,
    marketCap: 4200,
    eps: 11.2,
    peRatio: 11.2,
    revenueGrowth: 21.5,
    profitGrowth: 25.8,
    dividendYield: 3.5,
    debtToEquity: 0.28,
    bookValue: 98.5,
  },
  {
    ticker: 'LIBRA',
    name: 'Libra Infusions Limited',
    sector: 'Pharmaceuticals',
    basePrice: 52.5,
    trendBias: -0.08,
    volatility: 0.027,
    marketCap: 800,
    eps: 3.8,
    peRatio: 13.8,
    revenueGrowth: 4.2,
    profitGrowth: -3.5,
    dividendYield: 1.8,
    debtToEquity: 0.48,
    bookValue: 42.2,
  },
  {
    ticker: 'FINEFOODS',
    name: 'Fine Foods & Allied Ltd.',
    sector: 'Food & Allied',
    basePrice: 38.5,
    trendBias: -0.12,
    volatility: 0.03,
    marketCap: 600,
    eps: 2.5,
    peRatio: 15.4,
    revenueGrowth: 2.8,
    profitGrowth: -5.5,
    dividendYield: 1.2,
    debtToEquity: 0.58,
    bookValue: 28.5,
  },
  {
    ticker: 'OLYMPIC3',
    name: 'Olympic Accessories Ltd.',
    sector: 'Textile',
    basePrice: 42.8,
    trendBias: -0.15,
    volatility: 0.029,
    marketCap: 900,
    eps: 2.8,
    peRatio: 15.3,
    revenueGrowth: 3.2,
    profitGrowth: -6.8,
    dividendYield: 1.5,
    debtToEquity: 0.62,
    bookValue: 32.5,
  },
  {
    ticker: 'DELTALIFE',
    name: 'Delta Life Insurance Co.',
    sector: 'Insurance',
    basePrice: 48.5,
    trendBias: 0.08,
    volatility: 0.021,
    marketCap: 1500,
    eps: 5.2,
    peRatio: 9.3,
    revenueGrowth: 11.5,
    profitGrowth: 9.8,
    dividendYield: 5.2,
    debtToEquity: 0.18,
    bookValue: 42.5,
  },
  {
    ticker: 'SUNLIFE',
    name: 'Sunlife Insurance Limited',
    sector: 'Insurance',
    basePrice: 28.5,
    trendBias: -0.05,
    volatility: 0.025,
    marketCap: 700,
    eps: 2.8,
    peRatio: 10.2,
    revenueGrowth: 5.5,
    profitGrowth: -1.2,
    dividendYield: 3.0,
    debtToEquity: 0.2,
    bookValue: 25.8,
  },
  {
    ticker: 'GLAXOSMITH',
    name: 'GlaxoSmithKline BD Ltd.',
    sector: 'Pharmaceuticals',
    basePrice: 1582.5,
    trendBias: 0.15,
    volatility: 0.014,
    marketCap: 8500,
    eps: 125.8,
    peRatio: 12.6,
    revenueGrowth: 14.5,
    profitGrowth: 16.8,
    dividendYield: 4.5,
    debtToEquity: 0.15,
    bookValue: 1180.5,
  },
  {
    ticker: 'RECKITTBEN',
    name: 'Reckitt Benckiser BD Ltd.',
    sector: 'Food & Allied',
    basePrice: 285.8,
    trendBias: 0.12,
    volatility: 0.016,
    marketCap: 6200,
    eps: 24.5,
    peRatio: 11.7,
    revenueGrowth: 13.8,
    profitGrowth: 15.2,
    dividendYield: 5.8,
    debtToEquity: 0.22,
    bookValue: 220.5,
  },
  {
    ticker: 'BDTHAI',
    name: 'BD Thai Aluminum Ltd.',
    sector: 'Engineering',
    basePrice: 32.5,
    trendBias: -0.1,
    volatility: 0.028,
    marketCap: 800,
    eps: 2.5,
    peRatio: 13.0,
    revenueGrowth: 4.8,
    profitGrowth: -3.2,
    dividendYield: 1.8,
    debtToEquity: 0.55,
    bookValue: 25.8,
  },
  {
    ticker: 'BDWELDING',
    name: 'BD Welding Electrodes Ltd.',
    sector: 'Engineering',
    basePrice: 28.8,
    trendBias: 0.05,
    volatility: 0.026,
    marketCap: 600,
    eps: 2.2,
    peRatio: 13.1,
    revenueGrowth: 8.5,
    profitGrowth: 6.2,
    dividendYield: 2.5,
    debtToEquity: 0.48,
    bookValue: 22.5,
  },
  {
    ticker: 'BERGERPBL',
    name: 'Berger Paints Bangladesh Ltd.',
    sector: 'Engineering',
    basePrice: 1852.5,
    trendBias: 0.18,
    volatility: 0.015,
    marketCap: 7500,
    eps: 152.8,
    peRatio: 12.1,
    revenueGrowth: 16.5,
    profitGrowth: 18.8,
    dividendYield: 4.2,
    debtToEquity: 0.25,
    bookValue: 1380.5,
  },
  {
    ticker: 'BDLAMPS',
    name: 'BD Lamps Limited',
    sector: 'Engineering',
    basePrice: 48.5,
    trendBias: -0.08,
    volatility: 0.027,
    marketCap: 500,
    eps: 3.2,
    peRatio: 15.2,
    revenueGrowth: 3.5,
    profitGrowth: -4.2,
    dividendYield: 1.5,
    debtToEquity: 0.52,
    bookValue: 35.8,
  },
  {
    ticker: 'LHBL2',
    name: 'Lafarge Surma Cement Ltd.',
    sector: 'Cement',
    basePrice: 68.2,
    trendBias: 0.12,
    volatility: 0.022,
    marketCap: 8500,
    eps: 5.5,
    peRatio: 12.4,
    revenueGrowth: 14.5,
    profitGrowth: 16.2,
    dividendYield: 3.8,
    debtToEquity: 0.42,
    bookValue: 52.5,
  },
  {
    ticker: 'HEIDELBANGLA',
    name: 'Heidelberg Cement BD Ltd.',
    sector: 'Cement',
    basePrice: 385.8,
    trendBias: 0.08,
    volatility: 0.018,
    marketCap: 22000,
    eps: 32.5,
    peRatio: 11.9,
    revenueGrowth: 10.8,
    profitGrowth: 12.2,
    dividendYield: 5.5,
    debtToEquity: 0.2,
    bookValue: 295.5,
  },
  {
    ticker: 'ARL',
    name: 'Aramit Cement Limited',
    sector: 'Cement',
    basePrice: 185.5,
    trendBias: 0.05,
    volatility: 0.02,
    marketCap: 3200,
    eps: 15.8,
    peRatio: 11.7,
    revenueGrowth: 8.5,
    profitGrowth: 7.2,
    dividendYield: 4.2,
    debtToEquity: 0.35,
    bookValue: 148.5,
  },
  {
    ticker: 'CONFIDENCECEM',
    name: 'Confidence Cement Ltd.',
    sector: 'Cement',
    basePrice: 125.8,
    trendBias: 0.1,
    volatility: 0.023,
    marketCap: 2800,
    eps: 10.5,
    peRatio: 12.0,
    revenueGrowth: 12.8,
    profitGrowth: 14.5,
    dividendYield: 3.5,
    debtToEquity: 0.4,
    bookValue: 98.5,
  },
  {
    ticker: 'DIAMONDCEM',
    name: 'Diamond Cement Ltd.',
    sector: 'Cement',
    basePrice: 78.5,
    trendBias: -0.05,
    volatility: 0.025,
    marketCap: 1500,
    eps: 5.8,
    peRatio: 13.5,
    revenueGrowth: 4.2,
    profitGrowth: -2.8,
    dividendYield: 2.8,
    debtToEquity: 0.45,
    bookValue: 62.5,
  },
  {
    ticker: 'BSRMLTD',
    name: 'BSRM Steels Limited',
    sector: 'Engineering',
    basePrice: 52.8,
    trendBias: 0.15,
    volatility: 0.019,
    marketCap: 18000,
    eps: 5.2,
    peRatio: 10.2,
    revenueGrowth: 15.8,
    profitGrowth: 18.2,
    dividendYield: 4.5,
    debtToEquity: 0.38,
    bookValue: 45.8,
  },
  {
    ticker: 'BSRMSTEEL',
    name: 'BSRM Iron & Steel Co.',
    sector: 'Engineering',
    basePrice: 48.5,
    trendBias: 0.12,
    volatility: 0.02,
    marketCap: 6500,
    eps: 4.8,
    peRatio: 10.1,
    revenueGrowth: 14.2,
    profitGrowth: 15.8,
    dividendYield: 4.2,
    debtToEquity: 0.4,
    bookValue: 42.5,
  },
  {
    ticker: 'GPHOUSE2',
    name: 'GPH Ispat Limited',
    sector: 'Engineering',
    basePrice: 62.5,
    trendBias: 0.2,
    volatility: 0.021,
    marketCap: 8500,
    eps: 6.2,
    peRatio: 10.1,
    revenueGrowth: 22.5,
    profitGrowth: 25.8,
    dividendYield: 3.8,
    debtToEquity: 0.35,
    bookValue: 52.8,
  },
  {
    ticker: 'KDSAL',
    name: 'KDS Accessories Ltd.',
    sector: 'Textile',
    basePrice: 35.8,
    trendBias: -0.05,
    volatility: 0.026,
    marketCap: 1200,
    eps: 2.8,
    peRatio: 12.8,
    revenueGrowth: 5.2,
    profitGrowth: -2.5,
    dividendYield: 2.0,
    debtToEquity: 0.5,
    bookValue: 28.5,
  },
  {
    ticker: 'DELTICERAM',
    name: 'Delta Ceramics Ltd.',
    sector: 'Engineering',
    basePrice: 42.5,
    trendBias: 0.08,
    volatility: 0.024,
    marketCap: 1000,
    eps: 3.5,
    peRatio: 12.1,
    revenueGrowth: 10.2,
    profitGrowth: 8.5,
    dividendYield: 2.8,
    debtToEquity: 0.42,
    bookValue: 35.5,
  },
  {
    ticker: 'UNIQUE',
    name: 'Unique Construction Ltd.',
    sector: 'Engineering',
    basePrice: 28.5,
    trendBias: -0.1,
    volatility: 0.028,
    marketCap: 800,
    eps: 2.0,
    peRatio: 14.3,
    revenueGrowth: 3.8,
    profitGrowth: -4.5,
    dividendYield: 1.5,
    debtToEquity: 0.58,
    bookValue: 22.5,
  },
  {
    ticker: 'BDFOODS',
    name: 'BD Foods Limited',
    sector: 'Food & Allied',
    basePrice: 18.5,
    trendBias: 0.05,
    volatility: 0.025,
    marketCap: 1500,
    eps: 1.5,
    peRatio: 12.3,
    revenueGrowth: 9.8,
    profitGrowth: 8.2,
    dividendYield: 2.5,
    debtToEquity: 0.45,
    bookValue: 15.8,
  },
  {
    ticker: 'AMANFEED',
    name: 'Aman Feed Limited',
    sector: 'Food & Allied',
    basePrice: 52.8,
    trendBias: 0.18,
    volatility: 0.022,
    marketCap: 2800,
    eps: 4.8,
    peRatio: 11.0,
    revenueGrowth: 19.5,
    profitGrowth: 22.2,
    dividendYield: 3.2,
    debtToEquity: 0.38,
    bookValue: 42.5,
  },
  {
    ticker: 'QUASEM',
    name: 'Quasem Drycells Ltd.',
    sector: 'Engineering',
    basePrice: 78.5,
    trendBias: 0.05,
    volatility: 0.023,
    marketCap: 1200,
    eps: 6.2,
    peRatio: 12.7,
    revenueGrowth: 8.8,
    profitGrowth: 7.2,
    dividendYield: 3.0,
    debtToEquity: 0.4,
    bookValue: 62.5,
  },
  {
    ticker: 'BDGAS',
    name: 'BD Gas Limited',
    sector: 'Fuel & Energy',
    basePrice: 32.5,
    trendBias: 0.1,
    volatility: 0.019,
    marketCap: 2200,
    eps: 3.5,
    peRatio: 9.3,
    revenueGrowth: 12.8,
    profitGrowth: 10.5,
    dividendYield: 5.2,
    debtToEquity: 0.18,
    bookValue: 28.5,
  },
  {
    ticker: 'BAFL',
    name: 'BD Aviation Fuels Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 125.8,
    trendBias: 0.15,
    volatility: 0.02,
    marketCap: 3800,
    eps: 12.5,
    peRatio: 10.1,
    revenueGrowth: 16.2,
    profitGrowth: 18.5,
    dividendYield: 4.5,
    debtToEquity: 0.3,
    bookValue: 98.5,
  },
  {
    ticker: 'OLYMPIC4',
    name: 'Olympic Steel Ltd.',
    sector: 'Engineering',
    basePrice: 68.5,
    trendBias: 0.1,
    volatility: 0.022,
    marketCap: 2200,
    eps: 6.8,
    peRatio: 10.1,
    revenueGrowth: 12.5,
    profitGrowth: 14.2,
    dividendYield: 3.5,
    debtToEquity: 0.38,
    bookValue: 55.8,
  },
  {
    ticker: 'BDTHAI2',
    name: 'BD Thai Steel Ltd.',
    sector: 'Engineering',
    basePrice: 45.8,
    trendBias: 0.08,
    volatility: 0.024,
    marketCap: 1800,
    eps: 4.2,
    peRatio: 10.9,
    revenueGrowth: 10.5,
    profitGrowth: 8.8,
    dividendYield: 3.2,
    debtToEquity: 0.42,
    bookValue: 38.5,
  },
  {
    ticker: 'ACIL',
    name: 'ACI Containers Ltd.',
    sector: 'Engineering',
    basePrice: 38.5,
    trendBias: -0.05,
    volatility: 0.027,
    marketCap: 900,
    eps: 3.0,
    peRatio: 12.8,
    revenueGrowth: 5.5,
    profitGrowth: -2.2,
    dividendYield: 2.2,
    debtToEquity: 0.5,
    bookValue: 30.5,
  },
  {
    ticker: 'BXSYNTH',
    name: 'Beximco Synthetics Ltd.',
    sector: 'Textile',
    basePrice: 52.5,
    trendBias: 0.15,
    volatility: 0.021,
    marketCap: 2800,
    eps: 5.2,
    peRatio: 10.1,
    revenueGrowth: 16.8,
    profitGrowth: 18.5,
    dividendYield: 3.0,
    debtToEquity: 0.4,
    bookValue: 42.5,
  },
  {
    ticker: 'BXTEXT',
    name: 'Beximco Textiles Ltd.',
    sector: 'Textile',
    basePrice: 42.8,
    trendBias: 0.1,
    volatility: 0.023,
    marketCap: 3200,
    eps: 4.2,
    peRatio: 10.2,
    revenueGrowth: 12.5,
    profitGrowth: 10.8,
    dividendYield: 2.8,
    debtToEquity: 0.45,
    bookValue: 35.5,
  },
  {
    ticker: 'KARNAPHULI',
    name: 'Karnaphuli Insurance Ltd.',
    sector: 'Insurance',
    basePrice: 22.5,
    trendBias: 0.02,
    volatility: 0.024,
    marketCap: 600,
    eps: 2.2,
    peRatio: 10.2,
    revenueGrowth: 6.5,
    profitGrowth: 4.2,
    dividendYield: 3.5,
    debtToEquity: 0.2,
    bookValue: 20.5,
  },
  {
    ticker: 'PURABI',
    name: 'Purabi General Insurance',
    sector: 'Insurance',
    basePrice: 18.5,
    trendBias: -0.08,
    volatility: 0.026,
    marketCap: 400,
    eps: 1.5,
    peRatio: 12.3,
    revenueGrowth: 3.8,
    profitGrowth: -2.5,
    dividendYield: 2.5,
    debtToEquity: 0.25,
    bookValue: 16.8,
  },
  {
    ticker: 'NORTHERN',
    name: 'Northern Insurance Ltd.',
    sector: 'Insurance',
    basePrice: 32.8,
    trendBias: 0.1,
    volatility: 0.022,
    marketCap: 1000,
    eps: 3.8,
    peRatio: 8.6,
    revenueGrowth: 12.5,
    profitGrowth: 10.8,
    dividendYield: 4.8,
    debtToEquity: 0.15,
    bookValue: 28.5,
  },
  {
    ticker: 'PEOPLES',
    name: 'Peoples Insurance Ltd.',
    sector: 'Insurance',
    basePrice: 28.5,
    trendBias: 0.05,
    volatility: 0.023,
    marketCap: 800,
    eps: 3.2,
    peRatio: 8.9,
    revenueGrowth: 9.2,
    profitGrowth: 7.5,
    dividendYield: 4.2,
    debtToEquity: 0.18,
    bookValue: 25.8,
  },
  {
    ticker: 'ASIAPAC',
    name: 'Asia Pacific Insurance Ltd.',
    sector: 'Insurance',
    basePrice: 25.8,
    trendBias: -0.02,
    volatility: 0.025,
    marketCap: 500,
    eps: 2.8,
    peRatio: 9.2,
    revenueGrowth: 5.8,
    profitGrowth: 2.5,
    dividendYield: 3.2,
    debtToEquity: 0.22,
    bookValue: 22.5,
  },
  {
    ticker: 'BDCOM',
    name: 'BD Communications Ltd.',
    sector: 'Telecom',
    basePrice: 38.5,
    trendBias: 0.15,
    volatility: 0.022,
    marketCap: 1800,
    eps: 3.8,
    peRatio: 10.1,
    revenueGrowth: 16.5,
    profitGrowth: 18.2,
    dividendYield: 3.5,
    debtToEquity: 0.32,
    bookValue: 32.5,
  },
  {
    ticker: 'BDCOM2',
    name: 'BD Online Ltd.',
    sector: 'Telecom',
    basePrice: 22.5,
    trendBias: 0.2,
    volatility: 0.024,
    marketCap: 800,
    eps: 2.2,
    peRatio: 10.2,
    revenueGrowth: 22.5,
    profitGrowth: 25.8,
    dividendYield: 2.0,
    debtToEquity: 0.28,
    bookValue: 18.5,
  },
  {
    ticker: 'MERCANBANK',
    name: 'Mercantile Bank Ltd.',
    sector: 'Bank',
    basePrice: 20.5,
    trendBias: 0.1,
    volatility: 0.02,
    marketCap: 3800,
    eps: 2.5,
    peRatio: 8.2,
    revenueGrowth: 12.8,
    profitGrowth: 14.2,
    dividendYield: 3.8,
    debtToEquity: 0.8,
    bookValue: 23.5,
  },
  {
    ticker: 'SEBL',
    name: 'South East Bank Limited',
    sector: 'Bank',
    basePrice: 28.5,
    trendBias: 0.12,
    volatility: 0.019,
    marketCap: 5200,
    eps: 3.5,
    peRatio: 8.1,
    revenueGrowth: 14.5,
    profitGrowth: 16.2,
    dividendYield: 4.2,
    debtToEquity: 0.78,
    bookValue: 32.5,
  },
  {
    ticker: 'UCBL',
    name: 'United Commercial Bank Ltd.',
    sector: 'Bank',
    basePrice: 25.8,
    trendBias: 0.08,
    volatility: 0.02,
    marketCap: 4500,
    eps: 3.0,
    peRatio: 8.6,
    revenueGrowth: 11.2,
    profitGrowth: 9.8,
    dividendYield: 3.8,
    debtToEquity: 0.82,
    bookValue: 28.8,
  },
  {
    ticker: 'CITY2',
    name: 'City Bank PLC.',
    sector: 'Bank',
    basePrice: 22.8,
    trendBias: 0.18,
    volatility: 0.019,
    marketCap: 5800,
    eps: 2.8,
    peRatio: 8.1,
    revenueGrowth: 14.2,
    profitGrowth: 16.8,
    dividendYield: 4.2,
    debtToEquity: 0.8,
    bookValue: 26.5,
  },
  {
    ticker: 'NBL',
    name: 'National Bank Limited',
    sector: 'Bank',
    basePrice: 16.5,
    trendBias: -0.1,
    volatility: 0.023,
    marketCap: 2800,
    eps: 1.8,
    peRatio: 9.2,
    revenueGrowth: 4.2,
    profitGrowth: -3.5,
    dividendYield: 2.8,
    debtToEquity: 0.89,
    bookValue: 18.5,
  },
  {
    ticker: 'IFIC2',
    name: 'IFIC Bank PLC.',
    sector: 'Bank',
    basePrice: 9.8,
    trendBias: 0.05,
    volatility: 0.02,
    marketCap: 14200,
    eps: 1.2,
    peRatio: 8.2,
    revenueGrowth: 7.5,
    profitGrowth: 6.8,
    dividendYield: 4.5,
    debtToEquity: 0.85,
    bookValue: 14.5,
  },
  {
    ticker: 'BAITULMUKARRAM',
    name: 'Shahjalal Islami Bank Ltd.',
    sector: 'Bank',
    basePrice: 24.5,
    trendBias: 0.1,
    volatility: 0.02,
    marketCap: 4200,
    eps: 2.8,
    peRatio: 8.8,
    revenueGrowth: 12.8,
    profitGrowth: 14.5,
    dividendYield: 3.8,
    debtToEquity: 0.79,
    bookValue: 27.5,
  },
  {
    ticker: 'EXIM',
    name: 'EXIM Bank Limited',
    sector: 'Bank',
    basePrice: 12.5,
    trendBias: 0.05,
    volatility: 0.021,
    marketCap: 2200,
    eps: 1.4,
    peRatio: 8.9,
    revenueGrowth: 8.8,
    profitGrowth: 7.2,
    dividendYield: 3.2,
    debtToEquity: 0.83,
    bookValue: 14.8,
  },
  {
    ticker: 'MIDLAND',
    name: 'Midland Bank Limited',
    sector: 'Bank',
    basePrice: 8.5,
    trendBias: -0.05,
    volatility: 0.025,
    marketCap: 800,
    eps: 0.8,
    peRatio: 10.6,
    revenueGrowth: 4.5,
    profitGrowth: -2.8,
    dividendYield: 2.0,
    debtToEquity: 0.88,
    bookValue: 9.5,
  },
  {
    ticker: 'BANKASIA',
    name: 'Bank Asia Limited',
    sector: 'Bank',
    basePrice: 18.8,
    trendBias: 0.08,
    volatility: 0.02,
    marketCap: 2800,
    eps: 2.2,
    peRatio: 8.5,
    revenueGrowth: 10.5,
    profitGrowth: 9.2,
    dividendYield: 3.5,
    debtToEquity: 0.81,
    bookValue: 21.5,
  },
  {
    ticker: 'SOUTH BANGLA',
    name: 'South Bangla Agro & Commerce',
    sector: 'Bank',
    basePrice: 7.5,
    trendBias: -0.08,
    volatility: 0.026,
    marketCap: 600,
    eps: 0.6,
    peRatio: 12.5,
    revenueGrowth: 3.2,
    profitGrowth: -4.5,
    dividendYield: 1.8,
    debtToEquity: 0.9,
    bookValue: 8.2,
  },
  {
    ticker: 'IPDC',
    name: 'IPDC Finance Limited',
    sector: 'Financial Services',
    basePrice: 32.5,
    trendBias: 0.15,
    volatility: 0.021,
    marketCap: 3200,
    eps: 3.8,
    peRatio: 8.6,
    revenueGrowth: 15.2,
    profitGrowth: 17.8,
    dividendYield: 4.2,
    debtToEquity: 0.65,
    bookValue: 28.5,
  },
  {
    ticker: 'IDLC',
    name: 'IDLC Finance Limited',
    sector: 'Financial Services',
    basePrice: 52.8,
    trendBias: 0.18,
    volatility: 0.019,
    marketCap: 5800,
    eps: 6.2,
    peRatio: 8.5,
    revenueGrowth: 16.8,
    profitGrowth: 19.5,
    dividendYield: 4.8,
    debtToEquity: 0.6,
    bookValue: 48.5,
  },
  {
    ticker: 'UFLL',
    name: 'United Finance Limited',
    sector: 'Financial Services',
    basePrice: 28.5,
    trendBias: 0.05,
    volatility: 0.022,
    marketCap: 1500,
    eps: 3.2,
    peRatio: 8.9,
    revenueGrowth: 8.8,
    profitGrowth: 7.2,
    dividendYield: 3.8,
    debtToEquity: 0.7,
    bookValue: 25.5,
  },
  {
    ticker: 'LANKABAFIN',
    name: 'LankaBangla Finance Ltd.',
    sector: 'Financial Services',
    basePrice: 42.5,
    trendBias: 0.1,
    volatility: 0.023,
    marketCap: 2800,
    eps: 4.8,
    peRatio: 8.9,
    revenueGrowth: 12.8,
    profitGrowth: 14.2,
    dividendYield: 4.0,
    debtToEquity: 0.68,
    bookValue: 38.5,
  },
  {
    ticker: 'BDFINANCE',
    name: 'BD Finance & Investment',
    sector: 'Financial Services',
    basePrice: 18.5,
    trendBias: -0.05,
    volatility: 0.025,
    marketCap: 800,
    eps: 1.8,
    peRatio: 10.3,
    revenueGrowth: 5.2,
    profitGrowth: -1.8,
    dividendYield: 2.5,
    debtToEquity: 0.75,
    bookValue: 16.5,
  },
  {
    ticker: 'HFL',
    name: 'Housing Finance Ltd.',
    sector: 'Financial Services',
    basePrice: 38.8,
    trendBias: 0.08,
    volatility: 0.02,
    marketCap: 1800,
    eps: 4.2,
    peRatio: 9.2,
    revenueGrowth: 10.8,
    profitGrowth: 9.5,
    dividendYield: 4.5,
    debtToEquity: 0.55,
    bookValue: 35.5,
  },
  {
    ticker: 'BDSUMMIT',
    name: 'BD Summit Alliance Ltd.',
    sector: 'Services & Tourism',
    basePrice: 68.5,
    trendBias: 0.2,
    volatility: 0.02,
    marketCap: 3200,
    eps: 7.2,
    peRatio: 9.5,
    revenueGrowth: 22.5,
    profitGrowth: 25.8,
    dividendYield: 4.0,
    debtToEquity: 0.3,
    bookValue: 55.8,
  },
  {
    ticker: 'BDHOTELS',
    name: 'BD Hotels & Resorts Ltd.',
    sector: 'Services & Tourism',
    basePrice: 85.8,
    trendBias: 0.22,
    volatility: 0.021,
    marketCap: 4200,
    eps: 8.5,
    peRatio: 10.1,
    revenueGrowth: 25.2,
    profitGrowth: 28.5,
    dividendYield: 4.5,
    debtToEquity: 0.32,
    bookValue: 68.5,
  },
  {
    ticker: 'BDTRAVEL',
    name: 'BD Travel & Tours Ltd.',
    sector: 'Services & Tourism',
    basePrice: 32.5,
    trendBias: -0.1,
    volatility: 0.028,
    marketCap: 800,
    eps: 2.5,
    peRatio: 13.0,
    revenueGrowth: 3.8,
    profitGrowth: -5.2,
    dividendYield: 1.8,
    debtToEquity: 0.55,
    bookValue: 25.5,
  },
  {
    ticker: 'BDLOGISTICS',
    name: 'BD Logistics Ltd.',
    sector: 'Services & Tourism',
    basePrice: 48.5,
    trendBias: 0.12,
    volatility: 0.022,
    marketCap: 1800,
    eps: 4.8,
    peRatio: 10.1,
    revenueGrowth: 14.8,
    profitGrowth: 12.5,
    dividendYield: 3.5,
    debtToEquity: 0.38,
    bookValue: 42.5,
  },
  {
    ticker: 'BDMEDIA',
    name: 'BD Media Limited',
    sector: 'Services & Tourism',
    basePrice: 28.5,
    trendBias: 0.05,
    volatility: 0.024,
    marketCap: 1000,
    eps: 2.8,
    peRatio: 10.2,
    revenueGrowth: 8.2,
    profitGrowth: 6.5,
    dividendYield: 2.8,
    debtToEquity: 0.42,
    bookValue: 25.5,
  },
  {
    ticker: 'BDIT',
    name: 'BD IT Services Ltd.',
    sector: 'Technology',
    basePrice: 52.8,
    trendBias: 0.3,
    volatility: 0.023,
    marketCap: 2200,
    eps: 5.2,
    peRatio: 10.2,
    revenueGrowth: 28.5,
    profitGrowth: 32.2,
    dividendYield: 2.5,
    debtToEquity: 0.25,
    bookValue: 42.5,
  },
  {
    ticker: 'BDSOFT',
    name: 'BD Software Ltd.',
    sector: 'Technology',
    basePrice: 38.5,
    trendBias: 0.35,
    volatility: 0.025,
    marketCap: 1500,
    eps: 3.8,
    peRatio: 10.1,
    revenueGrowth: 32.5,
    profitGrowth: 35.8,
    dividendYield: 2.0,
    debtToEquity: 0.2,
    bookValue: 32.5,
  },
  {
    ticker: 'BDTECH',
    name: 'BD Technology Ltd.',
    sector: 'Technology',
    basePrice: 28.5,
    trendBias: 0.25,
    volatility: 0.026,
    marketCap: 1000,
    eps: 2.8,
    peRatio: 10.2,
    revenueGrowth: 25.2,
    profitGrowth: 28.5,
    dividendYield: 1.8,
    debtToEquity: 0.22,
    bookValue: 24.5,
  },
  {
    ticker: 'BDINFRA',
    name: 'BD Infrastructure Ltd.',
    sector: 'Engineering',
    basePrice: 42.5,
    trendBias: 0.15,
    volatility: 0.021,
    marketCap: 2800,
    eps: 4.2,
    peRatio: 10.1,
    revenueGrowth: 16.8,
    profitGrowth: 18.5,
    dividendYield: 3.5,
    debtToEquity: 0.4,
    bookValue: 35.8,
  },
  {
    ticker: 'BDPLASTIC',
    name: 'BD Plastic Industries Ltd.',
    sector: 'Engineering',
    basePrice: 22.5,
    trendBias: -0.05,
    volatility: 0.027,
    marketCap: 600,
    eps: 1.8,
    peRatio: 12.5,
    revenueGrowth: 4.8,
    profitGrowth: -3.2,
    dividendYield: 1.5,
    debtToEquity: 0.52,
    bookValue: 18.5,
  },
  {
    ticker: 'BDCHEM',
    name: 'BD Chemicals Limited',
    sector: 'Engineering',
    basePrice: 35.8,
    trendBias: 0.1,
    volatility: 0.022,
    marketCap: 1200,
    eps: 3.5,
    peRatio: 10.2,
    revenueGrowth: 12.2,
    profitGrowth: 10.8,
    dividendYield: 3.0,
    debtToEquity: 0.42,
    bookValue: 28.5,
  },
  {
    ticker: 'BDPAPER',
    name: 'BD Paper Mills Ltd.',
    sector: 'Engineering',
    basePrice: 28.8,
    trendBias: -0.08,
    volatility: 0.026,
    marketCap: 800,
    eps: 2.2,
    peRatio: 13.1,
    revenueGrowth: 3.5,
    profitGrowth: -4.8,
    dividendYield: 1.8,
    debtToEquity: 0.55,
    bookValue: 22.5,
  },
  {
    ticker: 'BDLTHAI',
    name: 'BD Lube Oil Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 85.8,
    trendBias: 0.12,
    volatility: 0.02,
    marketCap: 1800,
    eps: 8.5,
    peRatio: 10.1,
    revenueGrowth: 14.2,
    profitGrowth: 15.8,
    dividendYield: 4.2,
    debtToEquity: 0.28,
    bookValue: 68.5,
  },
  {
    ticker: 'BDOIL',
    name: 'BD Oil Industries Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 125.8,
    trendBias: 0.08,
    volatility: 0.019,
    marketCap: 3200,
    eps: 12.5,
    peRatio: 10.1,
    revenueGrowth: 10.8,
    profitGrowth: 9.2,
    dividendYield: 5.2,
    debtToEquity: 0.25,
    bookValue: 98.5,
  },
  {
    ticker: 'BDPETRO',
    name: 'BD Petroleum Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 68.5,
    trendBias: 0.15,
    volatility: 0.021,
    marketCap: 4200,
    eps: 6.8,
    peRatio: 10.1,
    revenueGrowth: 16.5,
    profitGrowth: 18.2,
    dividendYield: 4.5,
    debtToEquity: 0.3,
    bookValue: 55.8,
  },
  {
    ticker: 'BDGAS2',
    name: 'BD Natural Gas Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 48.5,
    trendBias: 0.1,
    volatility: 0.02,
    marketCap: 2800,
    eps: 4.8,
    peRatio: 10.1,
    revenueGrowth: 12.8,
    profitGrowth: 10.5,
    dividendYield: 5.0,
    debtToEquity: 0.22,
    bookValue: 42.5,
  },
  {
    ticker: 'BDPOWER',
    name: 'BD Power Generation Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 58.8,
    trendBias: 0.12,
    volatility: 0.019,
    marketCap: 5200,
    eps: 5.8,
    peRatio: 10.1,
    revenueGrowth: 14.5,
    profitGrowth: 16.2,
    dividendYield: 5.5,
    debtToEquity: 0.28,
    bookValue: 52.5,
  },
  {
    ticker: 'BDRENEW',
    name: 'BD Renewable Energy Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 42.5,
    trendBias: 0.28,
    volatility: 0.024,
    marketCap: 1800,
    eps: 4.2,
    peRatio: 10.1,
    revenueGrowth: 28.5,
    profitGrowth: 32.2,
    dividendYield: 2.5,
    debtToEquity: 0.32,
    bookValue: 35.8,
  },
  {
    ticker: 'BDSOLAR',
    name: 'BD Solar Power Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 32.5,
    trendBias: 0.32,
    volatility: 0.026,
    marketCap: 1200,
    eps: 3.2,
    peRatio: 10.2,
    revenueGrowth: 32.5,
    profitGrowth: 35.8,
    dividendYield: 2.0,
    debtToEquity: 0.28,
    bookValue: 28.5,
  },
  {
    ticker: 'BDWIND',
    name: 'BD Wind Energy Ltd.',
    sector: 'Fuel & Energy',
    basePrice: 28.5,
    trendBias: 0.25,
    volatility: 0.027,
    marketCap: 800,
    eps: 2.8,
    peRatio: 10.2,
    revenueGrowth: 25.2,
    profitGrowth: 28.5,
    dividendYield: 1.8,
    debtToEquity: 0.3,
    bookValue: 24.5,
  },
];

function generateHistory(seed: CompanySeed, rng: RNG): PricePoint[] {
  const points: PricePoint[] = [];
  const days = 260; // ~1 year of trading days
  let price = seed.basePrice * rng.range(0.75, 0.9);
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - days);

  for (let i = 0; i < days; i++) {
    const date = new Date(startDate);
    date.setDate(date.getDate() + i);
    // Skip weekends
    if (date.getDay() === 0 || date.getDay() === 6) continue;

    const trendComponent = seed.trendBias * 0.003;
    const noise = (rng.next() - 0.5) * 2 * seed.volatility;
    const change = trendComponent + noise;
    price = price * (1 + change);
    price = Math.max(price, 1);

    const baseVolume = seed.marketCap * 1000;
    const volume = Math.floor(baseVolume * rng.range(0.3, 1.8));

    points.push({
      date: date.toISOString().slice(0, 10),
      price: Math.round(price * 100) / 100,
      volume,
    });
  }
  return points;
}

const NEWS_TEMPLATES: { headline: string; sentiment: Sentiment; impact: Impact; summary: string }[] = [
  { headline: 'announces major factory expansion to boost production capacity', sentiment: 'POSITIVE', impact: 'HIGH', summary: 'The company plans to invest significantly in new manufacturing facilities, aiming to increase production capacity by 40% over the next two years.' },
  { headline: 'reports strong quarterly earnings, beating analyst expectations', sentiment: 'POSITIVE', impact: 'HIGH', summary: 'Quarterly results show revenue and profit growth exceeding market forecasts, driven by strong domestic demand and operational efficiency.' },
  { headline: 'declares interim dividend for shareholders', sentiment: 'POSITIVE', impact: 'MEDIUM', summary: 'The board has approved an interim dividend payout, reflecting confidence in the company financial position and commitment to shareholder returns.' },
  { headline: 'secures major government contract', sentiment: 'POSITIVE', impact: 'HIGH', summary: 'The company has been awarded a significant government procurement contract, expected to contribute meaningfully to future revenue.' },
  { headline: 'faces regulatory scrutiny over compliance issues', sentiment: 'NEGATIVE', impact: 'HIGH', summary: 'Regulatory authorities have raised concerns regarding compliance practices, potentially leading to fines or operational restrictions.' },
  { headline: 'reports decline in quarterly profit due to rising costs', sentiment: 'NEGATIVE', impact: 'MEDIUM', summary: 'Higher raw material costs and increased operating expenses have squeezed profit margins, with net profit declining quarter-over-quarter.' },
  { headline: 'launches new product line targeting emerging market', sentiment: 'POSITIVE', impact: 'MEDIUM', summary: 'The company has introduced a new product portfolio aimed at capturing demand in emerging consumer segments.' },
  { headline: 'board approves share buyback program', sentiment: 'POSITIVE', impact: 'MEDIUM', summary: 'The board has authorized a share repurchase program, signaling management belief that the stock is undervalued.' },
  { headline: 'warns of challenging market conditions ahead', sentiment: 'NEGATIVE', impact: 'HIGH', summary: 'Management has cautioned investors about headwinds from macroeconomic uncertainty and competitive pressure in the coming quarters.' },
  { headline: 'completes successful rights issue, raising capital', sentiment: 'NEUTRAL', impact: 'MEDIUM', summary: 'The rights issue was oversubscribed, providing fresh capital for expansion plans, though it may result in short-term EPS dilution.' },
  { headline: 'signs strategic partnership with international firm', sentiment: 'POSITIVE', impact: 'HIGH', summary: 'A new strategic alliance with a global partner is expected to enhance technology transfer and market access.' },
  { headline: 'reports flat revenue growth amid market slowdown', sentiment: 'NEUTRAL', impact: 'LOW', summary: 'Revenue remained largely unchanged compared to the prior period, reflecting a broader market slowdown.' },
];

const NEWS_SOURCES = ['DSE Newsroom', 'Financial Express', 'Dhaka Tribune Business', 'BSS Wire', 'The Business Standard'];

function generateNews(ticker: string, name: string, rng: RNG): NewsItem[] {
  const count = rng.int(3, 6);
  const items: NewsItem[] = [];
  const now = new Date();
  for (let i = 0; i < count; i++) {
    const template = rng.pick(NEWS_TEMPLATES);
    const daysAgo = rng.int(1, 30);
    const date = new Date(now);
    date.setDate(date.getDate() - daysAgo);
    const firstName = name.split(' ')[0];
    items.push({
      id: `${ticker}-news-${i}`,
      headline: `${firstName} ${template.headline}`,
      source: rng.pick(NEWS_SOURCES),
      date: date.toISOString().slice(0, 10),
      ticker,
      sentiment: template.sentiment,
      confidence: rng.int(65, 95),
      impact: template.impact,
      summary: template.summary,
    });
  }
  return items.sort((a, b) => b.date.localeCompare(a.date));
}

function computeAIScore(
  trendBias: number,
  technicals: ReturnType<typeof computeTechnicals>,
  fundamentals: CompanySeed,
  news: NewsItem[],
): AIScore {
  // Technical momentum: based on RSI, MACD, price vs SMA
  const rsiScore = technicals.rsi > 70 ? 65 : technicals.rsi < 30 ? 72 : 50 + (technicals.rsi - 50) * 0.8;
  const macdScore = 50 + technicals.macdHistogram * 20;
  const priceVsSma = fundamentals.basePrice > technicals.sma20 ? 65 : 45;
  const technicalMomentum = Math.round(Math.max(0, Math.min(100, (rsiScore + macdScore + priceVsSma) / 3 + trendBias * 15)));

  // Fundamental health
  const peScore = fundamentals.peRatio < 15 ? 75 : fundamentals.peRatio < 25 ? 60 : 40;
  const growthScore = Math.max(20, Math.min(95, 50 + fundamentals.revenueGrowth * 1.5 + fundamentals.profitGrowth));
  const divScore = fundamentals.dividendYield > 3 ? 75 : fundamentals.dividendYield > 1 ? 60 : 45;
  const debtScore = fundamentals.debtToEquity < 0.4 ? 80 : fundamentals.debtToEquity < 0.7 ? 60 : 40;
  const fundamentalHealth = Math.round((peScore + growthScore + divScore + debtScore) / 4);

  // Market trend
  const marketTrend = Math.round(Math.max(20, Math.min(95, 55 + trendBias * 40)));

  // News sentiment
  const positiveCount = news.filter((n) => n.sentiment === 'POSITIVE').length;
  const negativeCount = news.filter((n) => n.sentiment === 'NEGATIVE').length;
  const newsSentiment = Math.round(Math.max(20, Math.min(95, 50 + (positiveCount - negativeCount) * 15 + trendBias * 10)));

  // Volume (use a proxy from volatility)
  const volumeScore = Math.round(Math.max(30, Math.min(90, 60 + (0.025 - fundamentals.volatility) * 500)));

  // Risk
  const riskScore = Math.round(Math.max(20, Math.min(90, 70 - fundamentals.volatility * 500 - fundamentals.debtToEquity * 20)));

  const components = [
    { label: 'Technical Momentum', score: technicalMomentum, weight: 25 },
    { label: 'Fundamental Health', score: fundamentalHealth, weight: 25 },
    { label: 'Market Trend', score: marketTrend, weight: 15 },
    { label: 'News Sentiment', score: newsSentiment, weight: 15 },
    { label: 'Trading Volume', score: volumeScore, weight: 10 },
    { label: 'Risk / Volatility', score: riskScore, weight: 10 },
  ];

  const total = Math.round(components.reduce((acc, c) => acc + c.score * c.weight, 0) / 100);

  const signal = total >= 65 ? 'BUY' : total <= 45 ? 'AVOID' : 'HOLD';
  const confidence = Math.min(95, Math.max(50, total + 5));

  // Generate reasons
  const reasons: string[] = [];
  if (technicalMomentum > 65) reasons.push(`Positive technical momentum with RSI at ${technicals.rsi.toFixed(0)}`);
  if (technicals.macdHistogram > 0) reasons.push('MACD histogram positive, indicating bullish momentum');
  if (fundamentalHealth > 65) reasons.push(`Strong fundamentals with P/E of ${fundamentals.peRatio.toFixed(1)} and ${fundamentals.revenueGrowth.toFixed(1)}% revenue growth`);
  if (newsSentiment > 60) reasons.push(`${positiveCount} recent positive news items vs ${negativeCount} negative`);
  if (fundamentals.dividendYield > 3) reasons.push(`Attractive dividend yield of ${fundamentals.dividendYield.toFixed(1)}%`);
  if (fundamentals.profitGrowth > 15) reasons.push(`Profit growth of ${fundamentals.profitGrowth.toFixed(1)}% signals improving profitability`);
  if (marketTrend > 60) reasons.push('Stock is in an uptrend relative to recent moving averages');
  if (reasons.length === 0) reasons.push('Mixed signals across technical and fundamental indicators');

  const risks: string[] = [];
  if (technicals.rsi > 70) risks.push('RSI in overbought territory, pullback possible');
  if (technicals.rsi < 30) risks.push('RSI in oversold territory, further decline possible');
  if (fundamentals.volatility > 0.025) risks.push('High price volatility increases uncertainty');
  if (fundamentals.debtToEquity > 0.6) risks.push(`Elevated debt-to-equity ratio of ${fundamentals.debtToEquity.toFixed(2)}`);
  if (negativeCount > positiveCount) risks.push('Recent news sentiment skews negative');
  if (fundamentals.profitGrowth < 0) risks.push('Declining profitability trend');
  if (risks.length === 0) risks.push('Moderate market volatility may affect short-term performance');

  return { total, components, signal, confidence, reasons: reasons.slice(0, 5), risks: risks.slice(0, 3) };
}

function computeForecast(basePrice: number, trendBias: number, vol: number, aiScoreTotal: number): PriceForecast {
  const drift = trendBias * 0.02;
  const vol7 = vol * basePrice * Math.sqrt(7 / 260);
  const vol30 = vol * basePrice * Math.sqrt(30 / 260);

  const base7 = basePrice * (1 + drift * 7);
  const base30 = basePrice * (1 + drift * 30);

  const probPositive = Math.max(15, Math.min(90, 50 + trendBias * 35 + (aiScoreTotal - 50) * 0.3));
  const confidence: Confidence = aiScoreTotal > 70 ? 'HIGH' : aiScoreTotal > 50 ? 'MEDIUM' : 'LOW';
  const expectedVolatility = vol > 0.025 ? 'HIGH' : vol > 0.018 ? 'MEDIUM' : 'LOW';

  return {
    sevenDay: {
      bear: [Math.round((base7 - vol7 * 1.5) * 100) / 100, Math.round((base7 - vol7 * 0.5) * 100) / 100],
      base: [Math.round((base7 - vol7 * 0.5) * 100) / 100, Math.round((base7 + vol7 * 0.5) * 100) / 100],
      bull: [Math.round((base7 + vol7 * 0.5) * 100) / 100, Math.round((base7 + vol7 * 1.5) * 100) / 100],
    },
    thirtyDay: {
      bear: [Math.round((base30 - vol30 * 1.5) * 100) / 100, Math.round((base30 - vol30 * 0.5) * 100) / 100],
      base: [Math.round((base30 - vol30 * 0.5) * 100) / 100, Math.round((base30 + vol30 * 0.5) * 100) / 100],
      bull: [Math.round((base30 + vol30 * 0.5) * 100) / 100, Math.round((base30 + vol30 * 1.5) * 100) / 100],
    },
    probPositiveReturn: Math.round(probPositive),
    confidence,
    expectedVolatility,
  };
}

export function generateStocks(): Stock[] {
  return COMPANIES.map((seed, idx) => {
    const rng = new RNG((idx + 1) * 1000 + 42);
    const history = generateHistory(seed, rng);
    const lastPrice = history[history.length - 1].price;
    const prevPrice = history[history.length - 2].price;
    const dailyChange = Math.round((lastPrice - prevPrice) * 100) / 100;
    const dailyChangePct = Math.round((dailyChange / prevPrice) * 10000) / 100;

    const technicals = computeTechnicals(history);
    const news = generateNews(seed.ticker, seed.name, rng);
    const aiScore = computeAIScore(seed.trendBias, technicals, seed, news);
    const forecast = computeForecast(lastPrice, seed.trendBias, seed.volatility, aiScore.total);

    return {
      ticker: seed.ticker,
      name: seed.name,
      sector: seed.sector,
      currentPrice: lastPrice,
      dailyChange,
      dailyChangePct,
      volume: history[history.length - 1].volume,
      marketCap: seed.marketCap,
      history,
      fundamentals: {
        eps: seed.eps,
        peRatio: seed.peRatio,
        revenueGrowth: seed.revenueGrowth,
        profitGrowth: seed.profitGrowth,
        dividendYield: seed.dividendYield,
        debtToEquity: seed.debtToEquity,
        marketCap: seed.marketCap,
        bookValue: seed.bookValue,
      },
      technicals,
      aiScore,
      forecast,
      news,
    };
  });
}

export const SECTORS = [...new Set(COMPANIES.map((c) => c.sector))];
